[package]
name = "filewatcher_exporter"
version = "2.0.0"
edition = "2024"
authors = ["Egor Spivac <golden13@gmail.com>"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
log = "0.4.30"
env_logger = "0.7.1"
sysinfo = "0.9.6"
gethostname = "1.1.0"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
axum = "0.8.9"
clap-verbosity-flag = "3.0.4"
